### ISSUE TITLE
what this error means 

### ISSUE THREAD

**Issue by furjac** [sighook/pixload#20]
error: Invalid value "rules" for '--style <components>': Unknown style, 'rules'
![Screenshot_6](https://user-images.githubusercontent.com/81816200/196035341-21b951a2-2199-4e14-8e1e-ca1cbab3b1ed.png)

**Comment by juanpaynor** [comment]
This error message is indicating that the value "rules" is not a valid option for the '--style' parameter.

**Comment by furjac** [comment]
ok
